// BEGIN GENERATED SOLUTION METADATA
// Generated by the authorized Gemini solver pipeline.
// Problem: 001-two-sum
// LeetCode difficulty: easy
// Model: gemini-3.8-flash
// Effort: medium (thinkingLevel=medium)
// Temperature: 1.00 (legacy Gemini 2.x setting)
// Tokens (input/output/thinking/total): 566/461/613/1640
// Attempts: 1
// Solver wall time: 216.94s
// Jev model: jev-1.13.0
// Jev AI difficulty: easy (score=1.00/4, confidence=0.97)
// Jev assessment: state/assessments/001-two-sum.json
// END GENERATED SOLUTION METADATA
use std::collections::HashMap;

pub fn solve(nums: Vec<i32>, target: i32) -> Vec<i32> {
    let mut map = HashMap::with_capacity(nums.len());
    for (i, &num) in nums.iter().enumerate() {
        let complement = target - num;
        if let Some(&prev_idx) = map.get(&complement) {
            return vec![prev_idx as i32, i as i32];
        }
        map.insert(num, i);
    }
    vec![]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_examples() {
        assert_eq!(solve(vec![2, 7, 11, 15], 9), vec![0, 1]);
        assert_eq!(solve(vec![3, 2, 4], 6), vec![1, 2]);
        assert_eq!(solve(vec![3, 3], 6), vec![0, 1]);
    }

    #[test]
    fn test_negative_numbers() {
        assert_eq!(solve(vec![-1, -2, -3, -4, -5], -8), vec![2, 4]);
    }

    #[test]
    fn test_zero_target() {
        assert_eq!(solve(vec![-3, 4, 3, 90], 0), vec![0, 2]);
    }
}
