// BEGIN GENERATED SOLUTION METADATA
// Generated by the authorized Gemini solver pipeline.
// Problem: 002-add-two-numbers
// LeetCode difficulty: medium
// Model: gemini-3.8-flash
// Effort: medium (thinkingLevel=medium)
// Temperature: 1.00 (legacy Gemini 2.x setting)
// Tokens (input/output/thinking/total): 649/1056/578/2283
// Attempts: 1
// Solver wall time: 43.47s
// Jev model: jev-1.13.0
// Jev AI difficulty: easy (score=0.97/4, confidence=0.76)
// Jev assessment: state/assessments/002-add-two-numbers.json
// END GENERATED SOLUTION METADATA
#[derive(PartialEq, Eq, Clone, Debug)]
pub struct ListNode {
    pub val: i32,
    pub next: Option<Box<ListNode>>,
}

impl ListNode {
    #[inline]
    pub fn new(val: i32) -> Self {
        ListNode { next: None, val }
    }
}

pub fn add_two_numbers(
    mut l1: Option<Box<ListNode>>,
    mut l2: Option<Box<ListNode>>,
) -> Option<Box<ListNode>> {
    let mut dummy_head = ListNode::new(0);
    let mut tail = &mut dummy_head;
    let mut carry = 0;

    while l1.is_some() || l2.is_some() || carry != 0 {
        let mut sum = carry;

        if let Some(node) = l1 {
            sum += node.val;
            l1 = node.next;
        }

        if let Some(node) = l2 {
            sum += node.val;
            l2 = node.next;
        }

        carry = sum / 10;
        tail.next = Some(Box::new(ListNode::new(sum % 10)));
        tail = tail.next.as_mut().unwrap();
    }

    dummy_head.next
}

#[cfg(test)]
mod tests {
    use super::*;

    fn to_list(vals: &[i32]) -> Option<Box<ListNode>> {
        let mut head = None;
        for &val in vals.iter().rev() {
            let mut node = ListNode::new(val);
            node.next = head;
            head = Some(Box::new(node));
        }
        head
    }

    fn to_vec(mut head: Option<Box<ListNode>>) -> Vec<i32> {
        let mut res = Vec::new();
        while let Some(node) = head {
            res.push(node.val);
            head = node.next;
        }
        res
    }

    #[test]
    fn test_example_1() {
        let l1 = to_list(&[2, 4, 3]);
        let l2 = to_list(&[5, 6, 4]);
        let sum = add_two_numbers(l1, l2);
        assert_eq!(to_vec(sum), vec![7, 0, 8]);
    }

    #[test]
    fn test_example_2() {
        let l1 = to_list(&[0]);
        let l2 = to_list(&[0]);
        let sum = add_two_numbers(l1, l2);
        assert_eq!(to_vec(sum), vec![0]);
    }

    #[test]
    fn test_example_3() {
        let l1 = to_list(&[9, 9, 9, 9, 9, 9, 9]);
        let l2 = to_list(&[9, 9, 9, 9]);
        let sum = add_two_numbers(l1, l2);
        assert_eq!(to_vec(sum), vec![8, 9, 9, 9, 0, 0, 0, 1]);
    }

    #[test]
    fn test_different_lengths() {
        let l1 = to_list(&[1]);
        let l2 = to_list(&[9, 9]);
        let sum = add_two_numbers(l1, l2);
        assert_eq!(to_vec(sum), vec![0, 0, 1]);
    }
}
