// BEGIN GENERATED SOLUTION METADATA
// Generated by the authorized Gemini solver pipeline.
// Problem: 004-median-of-two-sorted-arrays
// LeetCode difficulty: hard
// Model: gemini-3.8-flash
// Effort: medium (thinkingLevel=medium)
// Temperature: 1.00 (legacy Gemini 2.x setting)
// Tokens (input/output/thinking/total): 2922/2135/1404/6461
// Attempts: 2
// Solver wall time: 62.76s
// Jev model: jev-1.13.0
// Jev AI difficulty: hard (score=3.08/4, confidence=0.82)
// Jev assessment: state/assessments/004-median-of-two-sorted-arrays.json
// END GENERATED SOLUTION METADATA
pub struct Solution;

impl Solution {
    pub fn find_median_sorted_arrays(nums1: Vec<i32>, nums2: Vec<i32>) -> f64 {
        let (a, b) = if nums1.len() <= nums2.len() {
            (&nums1, &nums2)
        } else {
            (&nums2, &nums1)
        };

        let m = a.len();
        let n = b.len();
        let mut low = 0;
        let mut high = m;
        let half_len = (m + n).div_ceil(2);

        while low <= high {
            let i = (low + high) / 2;
            let j = half_len - i;

            let a_left = if i > 0 { a[i - 1] } else { i32::MIN };
            let a_right = if i < m { a[i] } else { i32::MAX };
            let b_left = if j > 0 { b[j - 1] } else { i32::MIN };
            let b_right = if j < n { b[j] } else { i32::MAX };

            if a_left <= b_right && b_left <= a_right {
                let max_left = a_left.max(b_left);
                if (m + n) % 2 == 1 {
                    return max_left as f64;
                } else {
                    let min_right = a_right.min(b_right);
                    return (max_left as f64 + min_right as f64) / 2.0;
                }
            } else if a_left > b_right {
                high = i - 1;
            } else {
                low = i + 1;
            }
        }

        0.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_example_1() {
        let nums1 = vec![1, 3];
        let nums2 = vec![2];
        assert!((Solution::find_median_sorted_arrays(nums1, nums2) - 2.0).abs() < 1e-5);
    }

    #[test]
    fn test_example_2() {
        let nums1 = vec![1, 2];
        let nums2 = vec![3, 4];
        assert!((Solution::find_median_sorted_arrays(nums1, nums2) - 2.5).abs() < 1e-5);
    }

    #[test]
    fn test_one_empty_array() {
        let nums1 = vec![];
        let nums2 = vec![1];
        assert!((Solution::find_median_sorted_arrays(nums1, nums2) - 1.0).abs() < 1e-5);

        let nums1 = vec![2];
        let nums2 = vec![];
        assert!((Solution::find_median_sorted_arrays(nums1, nums2) - 2.0).abs() < 1e-5);
    }

    #[test]
    fn test_disjoint_ranges() {
        let nums1 = vec![1, 2, 3];
        let nums2 = vec![4, 5, 6];
        assert!((Solution::find_median_sorted_arrays(nums1, nums2) - 3.5).abs() < 1e-5);
    }

    #[test]
    fn test_negative_numbers() {
        let nums1 = vec![-5, -3, -1];
        let nums2 = vec![-2, 0, 2];
        assert!((Solution::find_median_sorted_arrays(nums1, nums2) - (-1.5)).abs() < 1e-5);
    }
}
