// BEGIN GENERATED SOLUTION METADATA
// Generated by the authorized Gemini solver pipeline.
// Problem: 006-zigzag-conversion
// LeetCode difficulty: medium
// Model: gemini-3.8-flash
// Effort: medium (thinkingLevel=medium)
// Temperature: 1.00 (legacy Gemini 2.x setting)
// Tokens (input/output/thinking/total): 630/793/857/2280
// Attempts: 1
// Solver wall time: 101.09s
// Jev model: jev-1.13.0
// Jev AI difficulty: easy (score=1.24/4, confidence=0.77)
// Jev assessment: state/assessments/006-zigzag-conversion.json
// END GENERATED SOLUTION METADATA
pub struct Solution;

impl Solution {
    pub fn convert(s: String, num_rows: i32) -> String {
        let num_rows = num_rows as usize;
        if num_rows <= 1 || num_rows >= s.len() {
            return s;
        }

        let mut rows: Vec<String> = vec![String::new(); num_rows];
        let mut cur_row = 0;
        let mut going_down = false;

        for c in s.chars() {
            rows[cur_row].push(c);
            if cur_row == 0 || cur_row == num_rows - 1 {
                going_down = !going_down;
            }
            if going_down {
                cur_row += 1;
            } else {
                cur_row -= 1;
            }
        }

        rows.concat()
    }
}

#[cfg(test)]
mod tests {
    use super::Solution;

    #[test]
    fn test_example_1() {
        let s = "PAYPALISHIRING".to_string();
        let num_rows = 3;
        assert_eq!(Solution::convert(s, num_rows), "PAHNAPLSIIGYIR");
    }

    #[test]
    fn test_example_2() {
        let s = "PAYPALISHIRING".to_string();
        let num_rows = 4;
        assert_eq!(Solution::convert(s, num_rows), "PINALSIGYAHRPI");
    }

    #[test]
    fn test_single_char_single_row() {
        let s = "A".to_string();
        let num_rows = 1;
        assert_eq!(Solution::convert(s, num_rows), "A");
    }

    #[test]
    fn test_multi_char_single_row() {
        let s = "AB".to_string();
        let num_rows = 1;
        assert_eq!(Solution::convert(s, num_rows), "AB");
    }

    #[test]
    fn test_num_rows_larger_than_length() {
        let s = "ABC".to_string();
        let num_rows = 5;
        assert_eq!(Solution::convert(s, num_rows), "ABC");
    }

    #[test]
    fn test_two_rows() {
        let s = "ABCD".to_string();
        let num_rows = 2;
        assert_eq!(Solution::convert(s, num_rows), "ACBD");
    }
}
