// BEGIN GENERATED SOLUTION METADATA
// Generated by the authorized Gemini solver pipeline.
// Problem: 007-reverse-integer
// LeetCode difficulty: medium
// Model: gemini-3.8-flash
// Effort: medium (thinkingLevel=medium)
// Temperature: 1.00 (legacy Gemini 2.x setting)
// Tokens (input/output/thinking/total): 463/596/674/1733
// Attempts: 1
// Solver wall time: 24.35s
// Jev model: jev-1.13.0
// Jev AI difficulty: moderate (score=1.50/4, confidence=0.46)
// Jev assessment: state/assessments/007-reverse-integer.json
// END GENERATED SOLUTION METADATA
pub struct Solution;

impl Solution {
    pub fn reverse(mut x: i32) -> i32 {
        let mut rev: i32 = 0;
        while x != 0 {
            let pop = x % 10;
            x /= 10;
            match rev.checked_mul(10).and_then(|r| r.checked_add(pop)) {
                Some(val) => rev = val,
                None => return 0,
            }
        }
        rev
    }
}

#[cfg(test)]
mod tests {
    use super::Solution;

    #[test]
    fn test_positive_number() {
        assert_eq!(Solution::reverse(123), 321);
    }

    #[test]
    fn test_negative_number() {
        assert_eq!(Solution::reverse(-123), -321);
    }

    #[test]
    fn test_trailing_zeros() {
        assert_eq!(Solution::reverse(120), 21);
        assert_eq!(Solution::reverse(-120), -21);
    }

    #[test]
    fn test_zero() {
        assert_eq!(Solution::reverse(0), 0);
    }

    #[test]
    fn test_single_digit() {
        assert_eq!(Solution::reverse(7), 7);
        assert_eq!(Solution::reverse(-7), -7);
    }

    #[test]
    fn test_overflow_cases() {
        assert_eq!(Solution::reverse(1534236469), 0);
        assert_eq!(Solution::reverse(-2147483648), 0);
        assert_eq!(Solution::reverse(2147483647), 0);
    }
}
