// BEGIN GENERATED SOLUTION METADATA
// Generated by the authorized Gemini solver pipeline.
// Problem: 008-string-to-integer-atoi
// LeetCode difficulty: medium
// Model: gemini-3.8-flash
// Effort: medium (thinkingLevel=medium)
// Temperature: 1.00 (legacy Gemini 2.x setting)
// Tokens (input/output/thinking/total): 1000/1110/479/2589
// Attempts: 1
// Solver wall time: 80.92s
// Jev model: jev-1.13.0
// Jev AI difficulty: moderate (score=1.65/4, confidence=0.55)
// Jev assessment: state/assessments/008-string-to-integer-atoi.json
// END GENERATED SOLUTION METADATA
pub struct Solution;

impl Solution {
    pub fn my_atoi(s: String) -> i32 {
        let bytes = s.as_bytes();
        let mut i = 0;
        let n = bytes.len();

        // 1. Skip leading whitespaces
        while i < n && bytes[i] == b' ' {
            i += 1;
        }

        if i == n {
            return 0;
        }

        // 2. Check for sign
        let mut sign: i64 = 1;
        if bytes[i] == b'-' {
            sign = -1;
            i += 1;
        } else if bytes[i] == b'+' {
            i += 1;
        }

        // 3. Convert digits with clamping
        let mut result: i64 = 0;
        let max_limit = i32::MAX as i64;
        let min_limit = i32::MIN as i64;

        while i < n && bytes[i].is_ascii_digit() {
            let digit = (bytes[i] - b'0') as i64;
            result = result * 10 + digit;

            if sign == 1 && result > max_limit {
                return i32::MAX;
            }
            if sign == -1 && -result < min_limit {
                return i32::MIN;
            }

            i += 1;
        }

        (sign * result) as i32
    }
}

#[cfg(test)]
mod tests {
    use super::Solution;

    #[test]
    fn test_examples() {
        assert_eq!(Solution::my_atoi("42".to_string()), 42);
        assert_eq!(Solution::my_atoi("   -042".to_string()), -42);
        assert_eq!(Solution::my_atoi("1337c0d3".to_string()), 1337);
        assert_eq!(Solution::my_atoi("0-1".to_string()), 0);
    }

    #[test]
    fn test_words_and_signs() {
        assert_eq!(Solution::my_atoi("words and 987".to_string()), 0);
        assert_eq!(Solution::my_atoi("+-12".to_string()), 0);
        assert_eq!(Solution::my_atoi("+".to_string()), 0);
        assert_eq!(Solution::my_atoi("-".to_string()), 0);
        assert_eq!(Solution::my_atoi("  +1".to_string()), 1);
    }

    #[test]
    fn test_overflow_and_underflow() {
        assert_eq!(Solution::my_atoi("-91283472332".to_string()), i32::MIN);
        assert_eq!(Solution::my_atoi("91283472332".to_string()), i32::MAX);
        assert_eq!(Solution::my_atoi("2147483647".to_string()), 2147483647);
        assert_eq!(Solution::my_atoi("-2147483648".to_string()), -2147483648);
        assert_eq!(Solution::my_atoi("2147483648".to_string()), 2147483647);
        assert_eq!(Solution::my_atoi("-2147483649".to_string()), -2147483648);
    }

    #[test]
    fn test_empty_and_spaces() {
        assert_eq!(Solution::my_atoi("".to_string()), 0);
        assert_eq!(Solution::my_atoi("     ".to_string()), 0);
    }
}
