// BEGIN GENERATED SOLUTION METADATA
// Generated by the authorized Gemini solver pipeline.
// Problem: 009-palindrome-number
// LeetCode difficulty: easy
// Model: gemini-3.8-flash
// Effort: medium (thinkingLevel=medium)
// Temperature: 1.00 (legacy Gemini 2.x setting)
// Tokens (input/output/thinking/total): 3742/817/1387/5946
// Attempts: 2
// Solver wall time: 218.41s
// Jev model: jev-1.13.0
// Jev AI difficulty: easy (score=0.78/4, confidence=0.77)
// Jev assessment: state/assessments/009-palindrome-number.json
// END GENERATED SOLUTION METADATA
pub struct Solution;

impl Solution {
    pub fn is_palindrome(x: i32) -> bool {
        if x < 0 || (x % 10 == 0 && x != 0) {
            return false;
        }

        let mut x = x;
        let mut reverted_number = 0;
        while x > reverted_number {
            reverted_number = reverted_number * 10 + x % 10;
            x /= 10;
        }

        x == reverted_number || x == reverted_number / 10
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_palindrome() {
        assert!(Solution::is_palindrome(121));
        assert!(!Solution::is_palindrome(-121));
        assert!(!Solution::is_palindrome(10));
        assert!(Solution::is_palindrome(0));
        assert!(Solution::is_palindrome(1221));
        assert!(Solution::is_palindrome(12321));
        assert!(!Solution::is_palindrome(123));
    }
}
