// BEGIN GENERATED SOLUTION METADATA
// Generated by the authorized Gemini solver pipeline.
// Problem: 010-regular-expression-matching
// LeetCode difficulty: hard
// Model: gemini-3.8-flash
// Effort: medium (thinkingLevel=medium)
// Temperature: 1.00 (legacy Gemini 2.x setting)
// Tokens (input/output/thinking/total): 3710/1819/1316/6845
// Attempts: 2
// Solver wall time: 186.55s
// Jev model: jev-1.13.0
// Jev AI difficulty: moderate (score=2.38/4, confidence=0.53)
// Jev assessment: state/assessments/010-regular-expression-matching.json
// END GENERATED SOLUTION METADATA
pub struct Solution;

impl Solution {
    pub fn is_match(s: String, p: String) -> bool {
        let s_bytes = s.as_bytes();
        let p_bytes = p.as_bytes();
        let m = s_bytes.len();
        let n = p_bytes.len();

        let mut dp = vec![vec![false; n + 1]; m + 1];
        dp[0][0] = true;

        for j in 1..=n {
            if p_bytes[j - 1] == b'*' {
                dp[0][j] = dp[0][j - 2];
            }
        }

        for i in 1..=m {
            for j in 1..=n {
                if p_bytes[j - 1] == b'*' {
                    let prev_pattern_char = p_bytes[j - 2];
                    let matches_prev =
                        prev_pattern_char == b'.' || prev_pattern_char == s_bytes[i - 1];
                    dp[i][j] = dp[i][j - 2] || (matches_prev && dp[i - 1][j]);
                } else if p_bytes[j - 1] == b'.' || p_bytes[j - 1] == s_bytes[i - 1] {
                    dp[i][j] = dp[i - 1][j - 1];
                }
            }
        }

        dp[m][n]
    }
}

#[cfg(test)]
mod tests {
    use super::Solution;

    #[test]
    fn test_examples() {
        assert!(!Solution::is_match("aa".to_string(), "a".to_string()));
        assert!(Solution::is_match("aa".to_string(), "a*".to_string()));
        assert!(Solution::is_match("ab".to_string(), ".*".to_string()));
    }

    #[test]
    fn test_multiple_stars() {
        assert!(Solution::is_match("aab".to_string(), "c*a*b".to_string()));
        assert!(!Solution::is_match(
            "mississippi".to_string(),
            "mis*is*p*.".to_string()
        ));
        assert!(Solution::is_match(
            "mississippi".to_string(),
            "mis*is*ip*.".to_string()
        ));
    }

    #[test]
    fn test_edge_cases() {
        assert!(Solution::is_match("a".to_string(), "ab*".to_string()));
        assert!(Solution::is_match("bbbba".to_string(), ".*a*a".to_string()));
        assert!(Solution::is_match("ab".to_string(), ".*..".to_string()));
        assert!(!Solution::is_match("ab".to_string(), ".*...".to_string()));
    }
}
