// BEGIN GENERATED SOLUTION METADATA
// Generated by the authorized Gemini solver pipeline.
// Problem: 011-container-with-most-water
// LeetCode difficulty: medium
// Model: gemini-3.8-flash
// Effort: medium (thinkingLevel=medium)
// Temperature: 1.00 (legacy Gemini 2.x setting)
// Tokens (input/output/thinking/total): 491/609/252/1352
// Attempts: 1
// Solver wall time: 9.12s
// Jev model: jev-1.13.0
// Jev AI difficulty: easy (score=1.20/4, confidence=0.84)
// Jev assessment: state/assessments/011-container-with-most-water.json
// END GENERATED SOLUTION METADATA
pub struct Solution;

impl Solution {
    pub fn max_area(height: Vec<i32>) -> i32 {
        let mut left = 0;
        let mut right = height.len() - 1;
        let mut max_water = 0;

        while left < right {
            let width = (right - left) as i32;
            let h = height[left].min(height[right]);
            let current_water = width * h;
            if current_water > max_water {
                max_water = current_water;
            }

            if height[left] < height[right] {
                left += 1;
            } else {
                right -= 1;
            }
        }

        max_water
    }
}

#[cfg(test)]
mod tests {
    use super::Solution;

    #[test]
    fn test_example_1() {
        let height = vec![1, 8, 6, 2, 5, 4, 8, 3, 7];
        assert_eq!(Solution::max_area(height), 49);
    }

    #[test]
    fn test_example_2() {
        let height = vec![1, 1];
        assert_eq!(Solution::max_area(height), 1);
    }

    #[test]
    fn test_zero_heights() {
        let height = vec![0, 0];
        assert_eq!(Solution::max_area(height), 0);
    }

    #[test]
    fn test_decreasing() {
        let height = vec![5, 4, 3, 2, 1];
        assert_eq!(Solution::max_area(height), 6);
    }

    #[test]
    fn test_identical_elements() {
        let height = vec![4, 4, 4, 4];
        assert_eq!(Solution::max_area(height), 12);
    }
}
