// BEGIN GENERATED SOLUTION METADATA
// Generated by the authorized Gemini solver pipeline.
// Problem: 012-integer-to-roman
// LeetCode difficulty: medium
// Model: gemini-3.8-flash
// Effort: medium (thinkingLevel=medium)
// Temperature: 1.00 (legacy Gemini 2.x setting)
// Tokens (input/output/thinking/total): 1100/699/565/2364
// Attempts: 1
// Solver wall time: 35.10s
// Jev model: jev-1.13.0
// Jev AI difficulty: easy (score=0.96/4, confidence=0.89)
// Jev assessment: state/assessments/012-integer-to-roman.json
// END GENERATED SOLUTION METADATA
pub struct Solution;

impl Solution {
    pub fn int_to_roman(mut num: i32) -> String {
        const MAPPINGS: [(i32, &str); 13] = [
            (1000, "M"),
            (900, "CM"),
            (500, "D"),
            (400, "CD"),
            (100, "C"),
            (90, "XC"),
            (50, "L"),
            (40, "XL"),
            (10, "X"),
            (9, "IX"),
            (5, "V"),
            (4, "IV"),
            (1, "I"),
        ];

        let mut result = String::new();
        for &(value, symbol) in &MAPPINGS {
            while num >= value {
                num -= value;
                result.push_str(symbol);
            }
        }
        result
    }
}

#[cfg(test)]
mod tests {
    use super::Solution;

    #[test]
    fn test_examples() {
        assert_eq!(Solution::int_to_roman(3749), "MMMDCCXLIX");
        assert_eq!(Solution::int_to_roman(58), "LVIII");
        assert_eq!(Solution::int_to_roman(1994), "MCMXCIV");
    }

    #[test]
    fn test_boundaries() {
        assert_eq!(Solution::int_to_roman(1), "I");
        assert_eq!(Solution::int_to_roman(3999), "MMMCMXCIX");
    }

    #[test]
    fn test_subtractive_forms() {
        assert_eq!(Solution::int_to_roman(4), "IV");
        assert_eq!(Solution::int_to_roman(9), "IX");
        assert_eq!(Solution::int_to_roman(40), "XL");
        assert_eq!(Solution::int_to_roman(90), "XC");
        assert_eq!(Solution::int_to_roman(400), "CD");
        assert_eq!(Solution::int_to_roman(900), "CM");
    }
}
